### PR TITLE
Added files for Viewsets Django

### PR DESCRIPTION
**Pull request by abhstabs**
@neil-vqa 

Hi, 
This is to allow creation of ModelViewsets too with the help of reactant. Please review the PR and let me know what all can be improved. I'm new to open source contribution so I'd like to have your feedback. 

Thanks.

### CODE REVIEW

**Comment by neil-vqa** [comment]
Hello! Thank you for taking the time to go through the code and contribute. I will do the review as soon as I can. :smiley:

**Review by neil-vqa — APPROVED** [review]
Looks good :ok_hand:

**Comment by neil-vqa** [comment]
Thank you for your contribution. :tada: :tada: I will include this in the release this week. @abhstabs

**Comment by abhstabs** [comment]
Thank you @neil-vqa 
Happy to contribute. 😄

**Pull request merged**
